# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremails',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useremails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
